### ISSUE TITLE
bugs si on ne met pas `connection.shared: true`

### ISSUE THREAD

**Issue by clemzarch** [php-etl/sql-plugin#21]
Avec sqlite, si on ne met pas `shared: true` dans la connection, on a soit des erreurs incompréhensibles, soit des chargements infini
```
- sql:
    connection:
        dsn: 'sqlite:bidule.sq3'
        shared: true
```
